### ISSUE TITLE
Duplicated "Ruleset" string in project and solution name

### ISSUE THREAD

**Issue by andy840119** [ppy/osu-templates#22] opened 2019-10-19 00:04 UTC
When i type 
```
dotnet new ruleset -n MyCoolRuleset
```
it appear `osu.Game.Rulesets.MyCoolRulesetRuleset` in `MyCoolRuleset` Folder
![image](https://user-images.githubusercontent.com/9100368/67134873-66a5f080-f24f-11e9-8652-583c7bbf51ad.png)

**Comment by andy840119** [comment] 2019-10-19 00:08
~~Wait it duplicated in #18~~

**Comment by frenzibyte** [comment] 2019-10-19 00:09
That's intended behaviour, there should be naming rules specified in the readme:
1. The name must always start with a capital letter, to avoid misleading class namings. Example:  Drawable**sample**Ruleset.
2. The name must never end with `Ruleset`, to avoid duplicated words in class namings as `Ruleset` is used a lot. Example: Drawable**SampleRuleset**Ruleset.

EDIT: Wait nevermind..., I didn't realize that's the solution name, Sorry.

**Comment by frenzibyte** [comment] 2019-10-19 00:31
This is already fixed on latest master with #18, but changes don't have a release yet. @peppy *ping*

**Comment by andy840119** [comment] 2019-10-19 00:39
It seems like #18 is just change the template replacement string from `EmptyFreeformRuleset` to `EmptyFreeform`
But it aims not solve this issue.

**Comment by frenzibyte** [comment] 2019-10-19 00:41
Have you tried latest master?

**Comment by andy840119** [comment] 2019-10-19 00:43
I cloned it yesterday 🤔

**Comment by peppy** [comment] 2019-10-19 00:44
I forgot that I need to release this package. Will look at automating releases.

**Comment by peppy** [comment] 2019-10-20 11:07
Release has been made, should fix this.

**Closed as completed** 2019-10-20 11:07 UTC

**Comment by andy840119** [comment] 2019-10-20 14:42
It works 👍
